# Generated by Django 5.1.5 on 2025-01-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('correct_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretsofthesourcecode_game.room')),
                ('correct_suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretsofthesourcecode_game.suspect')),
                ('correct_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretsofthesourcecode_game.weapon')),
            ],
        ),
    ]
